Creating skeleton loader
algolia/algolia-react-boilerplate pull request #247
Opened 2022-07-01 10:30 UTC by diegolarraz

## Objective
What: Skeleton loader
Why: Because the application is so fast that we need placeholders (which you can barely see) instead of animations as animations slow the UI down

## Type

- [x] New Feature

## Tested

Localhost

2022-07-01 14:44 UTC, HugoWith commented
Hellooo
Well done guys @diegolarraz @BenDanielGreep 

What do you think of having it for the facets and the federated search ? 😊

2022-07-04 07:01 UTC, matthew1809 requested changes
Nice work!

2022-07-04 07:01 UTC, matthew1809 commented on src/components/searchresultpage/srpLaptop/SrpLaptop.jsx
> +        {false && queryState === "" && (
why false, what is false? Can you please comment code which might not make sense to a new reader? Thanks!

2022-07-04 07:01 UTC, matthew1809 commented on src/components/trending/TrendingFacetValues.jsx
> +                      <div className="" key={i + "loader"} style={{width: "200px", height: "300px", backgroundColor: "green"}}></div>
maybe move this to a CSS class?

2022-07-04 07:01 UTC, matthew1809 commented on src/scss/searchresultspage/searchresultspage.scss
> +  // animation: fadeIn 3s forwards cubi÷c-bezier(0.43, 0.13, 0.23, 0.96);
Why comment and not remove?

2022-07-04 08:47 UTC, BenDanielGreep commented
> Hellooo Well done guys @diegolarraz @BenDanielGreep
> 
> What do you think of having it for the facets and the federated search ? 😊

We do have it for the facets (on SRP)

We talked about this - in our opinion it is so fast that no one will need the skeleton on FS. 
However for the fringe case that the SE computer is running slow, we could implement the skeleton on FS on another sprint :)

2022-07-04 09:02 UTC, VirAlex commented
Well done nice work, to me it's so fast I have no time to see skeleton 👍

2022-07-04 09:04 UTC, VirAlex requested changes

2022-07-04 09:04 UTC, VirAlex commented on src/components/searchresultpage/srpLaptop/SrpLaptop.jsx
> +import SkeletonLoader from '../../hits/HitsSkeletonLoader';
You can remove it because it's imported twice 👍

2022-07-04 09:09 UTC, VirAlex requested changes

2022-07-04 09:09 UTC, VirAlex commented on src/components/hits/components/HitsSkeletonLoader.jsx
> +import CustomSkeleton from '../skeletons/CustomSkeleton';
You can use absolut import: 
'@/....'

More easy 👍

2022-07-04 10:01 UTC, diegolarraz commented
You really cannot see the skeleton - it's too fast, and for some reason the InjectedHits component does not mount the fallback component. It mounts on CustomHits and Facets. Very strange.

An improvement from the fade in animation though

2022-07-04 10:12 UTC, matthew1809 approved these changes
LGTM!

2022-07-04 10:24 UTC, merged