Feat/query cat
algolia/algolia-react-boilerplate pull request #582
Opened 2023-02-22 16:43 UTC by VirAlex

## CAREFUL 🚨
Are you adding a new feature/fix/style tweak? 
If yes push to **develop branch** not on **main branch**

## Versioning
- [x] Are you sure you are pushing on the right branch?

## Objective

What: Integration of query cat for the boilerplate
Why: Last and key feature
How: I decided to integrate it in a part of the Federated Search, quite like the demo of query cat :[demo](https://query-categorization-demo.netlify.app/)
Usage:
You can type ambiguous terms, or not ambiguous the render will check if the probability is superior by default to 0.6, but you can define it in the config file:
`
// Change here your probability to show the query category by default prediction score > 60 will be displayed
export const probabilityToShowQueryCat = atom({
  key: 'probabilityToShowQueryCat', // unique ID (with respect to other atoms/selectors)
  default: 0.6, // default value (aka initial value)
})
`
Then to test it you have all the query terms at this [link](https://www.algolia.com/apps/853MYZ81KY/query-categorization/flagship_fashion/predictions)

You can use: 
- CARDIGAN ( ambiguous with results > 0.6 and not)
- Trousers (ambiguous but low results)
- WOMAN PANTS or HIGH HEELS unique result but more than 0.6
- VEST unique result less than 0.6

![Screenshot 2023-02-22 at 17 42 19](https://user-images.githubusercontent.com/22235112/220696641-09a1799f-42ef-4042-b266-2147451186ff.png)

## Type

- [x] New Feature

## Tested

✅

## Documented

- [x] Have you documented in a changed file using comments
- [ ] Have you added instructions to the README if needed?

2023-02-22 16:53 UTC, VirAlex commented on apps/boilerplate-front-end/README.md
> +<h3 style="font-family='Helvetica'; font-size=15px; font-weight=bold; color=grey;">📈 Query Categorization</h3>
With the readme it's better 🙏

2023-02-23 16:37 UTC, HugoWith requested changes
Hello, 
Thanks @VirAlex  for this feature ! Super cool. 
Here are my feedbacks : 
-  Please be consistent in font family & font size
<img width="813" alt="Screenshot 2023-02-23 at 17 01 02" src="https://user-images.githubusercontent.com/47173348/220962314-c5d4ba37-553f-4446-8c1e-8cab416019e2.png">

- Be consistent when hovering the category (black bold hover)
<img width="687" alt="Screenshot 2023-02-23 at 17 03 36" src="https://user-images.githubusercontent.com/47173348/220962909-2cfae254-a916-49df-93e5-1fb5f0258404.png">

- On click on the categories for query "dress" I'm landing on SRP with the right query and I suppose the right category but I don't see that in the current refinements
<img width="595" alt="Screenshot 2023-02-23 at 17 06 09" src="https://user-images.githubusercontent.com/47173348/220963608-a442e8cf-1aed-4c97-a1c3-05b1d7511724.png">


Otherwise I think it's all good 👌

2023-02-24 09:12 UTC, VirAlex commented on apps/boilerplate-front-end/src/components/federatedSearch/SCSS/federatedSearch.scss
>          @include p-text-federated($main-color);
Add hover partial @HugoWith

2023-02-24 09:13 UTC, VirAlex commented on apps/boilerplate-front-end/src/components/federatedSearch/SCSS/federatedSearch.scss
> +      font-size: 0.8rem;
Put the Font size and weight without partial because of the Hove I didn't want on the query

2023-02-24 09:23 UTC, merged